# This is a basic workflow to help you get started with Actions

name: puep-dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: puep-dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9
        env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: 'terraform'
          AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Runs a single command using the runners shell
      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan
