name: Deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
env:
  TF_WORKSPACE: "dev"
  AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ap-southeast-1
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9
      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
  setup:
    runs-on: ubuntu-latest
    needs: terraform-plan
    steps:
      - uses: actions/checkout@v2
      - uses: mskelton/setup-yarn@v1
        with:
          node-version: '16.x'
      - name: Yarn Installation
        run: yarn
      - name: Yarn Build
        run: yarn build