name: terraform-deploy
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  plan:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ap-southeast-1
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.9
      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve